export const CACHE_TIME = {
  ONE_MINUTE: 1 * 60 * 1000,
  TWO_MINUTES: 2 * 60 * 1000,
  THREE_MINUTES: 3 * 60 * 1000,
  FIVE_MINUTES: 5 * 60 * 1000,
  FIFTEEN_MINUTES: 15 * 60 * 1000,
  THIRTY_MINUTES: 30 * 60 * 1000,
  ONE_HOUR: 60 * 60 * 1000,
  TWENTY_FOUR_HOURS: 24 * 60 * 60 * 1000
}

export const CACHE_TYPE = {
  GLOBAL: 'GLOBAL',
  SENSITIVE: 'SENSITIVE',
  NONE: 'NONE'
}

export const GLOBAL_OPTIONS = {
  staleTime: CACHE_TIME.FIVE_MINUTES,
  gcTime: CACHE_TIME.THIRTY_MINUTES,
  refetchInterval: CACHE_TIME.FIVE_MINUTES,
  encrypted: false
}

export const SENSITIVE_OPTIONS = {
  staleTime: CACHE_TIME.TWO_MINUTES,
  gcTime: CACHE_TIME.FIVE_MINUTES,
  refetchInterval: CACHE_TIME.FIVE_MINUTES,
  encrypted: true
}

export const GC_OPTIONS = {
  INTERVAL: CACHE_TIME.THIRTY_MINUTES,
  ENABLED: true
}
