<template>
  <ContentBlock>
    <template #heading>
      <div class="flex items-start justify-between gap-4">
        <PageHeadingBlock
          pageTitle="Real-Time Events"
          description="Analyze real-time events and logs generated by Azion's products."
          :tag="previewTag"
        />
        <VersionToggle current="v2" />
      </div>
    </template>
    <template #content>
      <!-- Tab bar -->
      <div
        class="flex align-center justify-between relative"
        data-testid="session-toolbar"
      >
        <TabView
          :activeIndex="activeIndex"
          :scrollable="true"
          class="rte-events-tabview flex-1 min-w-0"
          @tab-click="onTabClick"
        >
          <TabPanel
            v-for="tab in combinedOpenTabs"
            :key="tab.id ?? 'events'"
            :pt="{
              root: { 'data-testid': `rte-tab-${tab.id ?? 'events'}` }
            }"
          >
            <template #header>
              <SessionTabHeader
                :tab="tab"
                :active="(tab.id ?? null) === (activeTabId ?? null)"
                :renameable="isEventsTabId(tab.id)"
                @close="handleCloseTab"
                @rename="(tabId, label) => renameEventsTab(tabId, label)"
              />
            </template>
          </TabPanel>
        </TabView>
        <div class="flex items-center gap-1 ml-4">
          <PrimeButton
            icon="pi pi-folder"
            text
            aria-label="Add to tabs"
            data-testid="open-session-browser-button"
            v-tooltip.bottom="{ value: 'Add session to tabs', showDelay: 300 }"
            @click="sessionBrowserVisible = true"
          />
          <PrimeButton
            icon="pi pi-share-alt"
            text
            aria-label="Share current view"
            data-testid="share-current-view-button"
            v-tooltip.bottom="{ value: 'Copy share link', showDelay: 300 }"
            @click="handleShare"
          />
        </div>
      </div>

      <!-- Tab contents (KeepAlive preserves per-tab state) -->
      <div class="mt-3">
        <KeepAlive>
          <TabPanelBlock
            v-if="!activeTabId"
            key="tab-events"
            ref="tabPanelBlockRef"
            :listService="selectedTabProps.listService"
            :filterFields="generatedFilterFields"
            :tabSelected="selectedTab"
            :loadEventsChartAggregation="loadEventsChartAggregation"
            :tabId="null"
            :activeTabId="activeTabId"
            :initialFilterState="pendingShareViewState?.filters"
            :initialPageSize="pendingShareViewState?.pageSize"
            :initialSelectedFields="pendingShareViewState?.selectedFields"
            @dataset-change="handleDatasetChange"
          />
          <TabPanelBlock
            v-else-if="isEventsTabId(activeTabId)"
            :key="`tab-${activeTabId}`"
            ref="tabPanelBlockRef"
            :listService="selectedTabProps.listService"
            :filterFields="generatedFilterFields"
            :tabSelected="selectedTab"
            :loadEventsChartAggregation="loadEventsChartAggregation"
            :tabId="activeTabId"
            :activeTabId="activeTabId"
            :pendingViewState="getPendingViewState(activeTabId)"
            @dataset-change="handleDatasetChange"
          />
          <DashboardPanel
            v-else-if="activePanelConfig"
            :key="`tab-${activeTabId}`"
            :panelConfig="activePanelConfig"
            :listEventsService="dashboardListService"
            :filterFields="generatedFilterFields"
            :loadEventsChartAggregation="loadEventsChartAggregation"
          />
        </KeepAlive>
      </div>

      <!-- Session Browser Sidebar (picker) — readOnly while custom sessions
           are disabled; Edit/Delete controls are hidden from the UI. -->
      <SessionBrowser
        v-model:visible="sessionBrowserVisible"
        :panels="panels"
        :activePanel="activeTabId"
        :readOnly="true"
        @select="handleBrowserSelect"
        @edit="editSession"
        @delete="deleteSession"
      />

      <!-- Session Creator Dialog -->
      <SessionCreator
        v-model:visible="sessionCreatorVisible"
        :panelConfig="editingPanel"
        :availableReports="availableReports"
        @save="handleSessionSave"
      />

      <!-- Fallback Copy Dialog — surfaced by `shareCurrentView()` when the
           Clipboard API is unavailable (insecure context, denied permission,
           private mode in some browsers). Stays mounted at the page root so
           the imperative `show(url)` from the composable works regardless of
           which tab is active. -->
      <FallbackCopyDialog ref="fallbackCopyDialogRef" />
    </template>
  </ContentBlock>
</template>

<script setup>
  import ContentBlock from '@/templates/content-block'
  import PageHeadingBlock from '@/templates/page-heading-block'
  import PrimeButton from '@aziontech/webkit/button'
  import VersionToggle from '@/views/RealTimeEvents/VersionToggle.vue'
  import TabView from 'primevue/tabview'
  import TabPanel from '@aziontech/webkit/tabpanel'
  import { computed, ref, onMounted, watch } from 'vue'
  import { useRoute, useRouter } from 'vue-router'
  import { useToast } from '@aziontech/webkit/use-toast'
  import TabPanelBlock from '@/views/RealTimeEventsV2/Blocks/tab-panel-block.vue'
  import SessionBrowser from '@/views/RealTimeEventsV2/Blocks/components/session-browser.vue'
  import SessionCreator from '@/views/RealTimeEventsV2/Blocks/components/session-creator.vue'
  import DashboardPanel from '@/views/RealTimeEventsV2/Blocks/components/dashboard-panel.vue'
  import SessionTabHeader from '@/views/RealTimeEventsV2/Blocks/components/session-tab-header.vue'
  import FallbackCopyDialog from '@/views/RealTimeEventsV2/components/FallbackCopyDialog.vue'
  import TABS_EVENTS from '@/views/RealTimeEventsV2/Blocks/constants/tabs-events'
  import { loadEventsFilterFields } from '@/modules/filter-loaders'
  import { useSessionManager } from '@/views/RealTimeEventsV2/composables/useSessionManager'
  import { useTabLimit } from '@/views/RealTimeEventsV2/composables/useTabLimit'
  import { useEventsTabs } from '@/views/RealTimeEventsV2/composables/useEventsTabs'

  defineOptions({ name: 'RealTimeEventsTabsView' })

  const previewTag = { value: 'Preview', severity: 'info' }

  const toast = useToast()

  const props = defineProps({
    httpRequests: {
      type: Object,
      required: true
    },
    edgeFunctions: {
      type: Object,
      required: true
    },
    edgeFunctionsConsole: {
      type: Object,
      required: true
    },
    activityHistory: {
      type: Object,
      required: true
    },
    dataStream: {
      type: Object,
      required: true
    },
    edgeDNS: {
      type: Object,
      required: true
    },
    imageProcessor: {
      type: Object,
      required: true
    },
    tieredCache: {
      type: Object,
      required: true
    },
    loadEventsChartAggregation: {
      type: Function,
      required: true
    }
  })

  const route = useRoute()
  const router = useRouter()

  // ── Existing state ──
  const tabPanelBlockRef = ref(null)
  const generatedFilterFields = ref([])
  const selectedDatasetKey = ref(null)
  // Ref to `<FallbackCopyDialog>` — wired into `useSessionManager` so the
  // composable can imperatively `show(url)` when the Clipboard API is
  // unavailable. Declared *before* the composable call so the ref is the
  // same identity Vue will populate after mount.
  const fallbackCopyDialogRef = ref(null)

  // ── Session management (composable) ──
  const {
    activeTabId,
    openTabs,
    panels,
    sessionBrowserVisible,
    sessionCreatorVisible,
    editingPanel,
    availableReports,
    activePanelConfig,
    pendingShareViewState,
    pendingEventsTabState,
    openTab,
    closeTab,
    setActiveTab,
    handleSessionSave,
    editSession,
    deleteSession,
    shareCurrentView,
    initializePanels
  } = useSessionManager({ route, router, toast, fallbackCopyDialogRef })

  // Backwards-compat alias for watchers below
  const activePanel = activeTabId

  // ── Additional Events tabs ──
  const {
    eventsTabs,
    openEventsTab,
    closeEventsTab,
    renameEventsTab,
    restoreEventsTabs,
    getPendingViewState,
    isEventsTabId
  } = useEventsTabs({
    toast,
    totalTabCount: () => {
      // Count: 1 (pinned) + additional Events tabs + Dashboard tabs
      return 1 + eventsTabs.value.length + openTabs.value.filter((tab) => tab.id !== null).length
    },
    activeTabId
  })

  // ── Tab limit (shared across all tab kinds) ──
  const { MAX_TOTAL_TABS, canOpenNewTab } = useTabLimit({
    openTabs: computed(() => [
      { id: null },
      ...eventsTabs.value,
      ...openTabs.value.filter((tab) => tab.id !== null)
    ])
  })

  // ── Combined tab list for the tab bar ──
  const combinedOpenTabs = computed(() => [
    { id: null, label: 'Events', icon: 'pi pi-list', closable: false },
    ...eventsTabs.value.map((tab) => ({
      id: tab.id,
      label: tab.label,
      icon: 'pi pi-list',
      closable: true
    })),
    ...openTabs.value.filter((tab) => tab.id !== null)
  ])

  // ── Tab UI helpers ──
  const activeIndex = computed(() =>
    combinedOpenTabs.value.findIndex((tab) => (tab.id ?? null) === (activeTabId.value ?? null))
  )

  const onTabClick = ({ index }) => {
    const tab = combinedOpenTabs.value[index]
    if (!tab) return
    if (tab.id === null) {
      setActiveTab(null)
    } else {
      setActiveTab(tab.id)
    }
  }

  const handleCloseTab = (tabId) => {
    if (isEventsTabId(tabId)) {
      closeEventsTab(tabId)
    } else {
      closeTab(tabId)
    }
  }

  const handleBrowserSelect = (panelId) => {
    if (panelId === null) {
      // "Events" item selected from the drawer — open a new Events tab
      openNewEventsTab()
    } else {
      openTab(panelId)
    }
    sessionBrowserVisible.value = false
  }

  // ── New Events tab button handler ──
  const openNewEventsTab = () => {
    const defaultDataset = Object.values(TABS_EVENTS)[0]?.panel || 'httpRequests'
    openEventsTab({ dataset: defaultDataset })
  }

  // ── Share ──
  // `shareCurrentView` is now async (Task 4.1 — awaits clipboard write so
  // the success toast only fires after the OS clipboard accepted the URL).
  // We await it here so any error surfaced by the composable's catch block
  // settles before the click handler returns — and so future enhancements
  // (analytics, focus restoration) can chain off the resolved promise.
  const handleShare = async () => {
    let viewState = {}
    let eventsTab = null

    if (tabPanelBlockRef.value?.getCurrentShareState) {
      viewState = tabPanelBlockRef.value.getCurrentShareState()
    }

    if (activeTabId.value && isEventsTabId(activeTabId.value)) {
      const tab = eventsTabs.value.find((entry) => entry.id === activeTabId.value)
      if (tab) {
        eventsTab = { id: tab.id, label: tab.label, dataset: tab.dataset }
      }
    }

    await shareCurrentView({ viewState, eventsTab })
  }

  // ── Watch pendingEventsTabState from useSessionManager (Share_State import) ──
  watch(pendingEventsTabState, (state) => {
    if (!state) return
    if (canOpenNewTab()) {
      openEventsTab({ label: state.label, dataset: state.dataset, viewState: state.viewState })
    } else {
      toast.add({
        closable: true,
        severity: 'warn',
        summary: `Tab limit reached (${MAX_TOTAL_TABS}). Close a tab before opening another one.`,
        life: 4000
      })
      // Apply viewState to pinned tab as fallback
      if (tabPanelBlockRef.value?.applyInitialShareState) {
        tabPanelBlockRef.value.applyInitialShareState()
      }
    }
    pendingEventsTabState.value = null
  })

  // All available datasets
  const allDatasets = Object.values(TABS_EVENTS)

  // Currently selected tab/dataset (for Log Explorer)
  const selectedTab = computed(() => {
    // When an additional Events tab is active, use its dataset
    if (activeTabId.value && isEventsTabId(activeTabId.value)) {
      const evTab = eventsTabs.value.find((entry) => entry.id === activeTabId.value)
      if (evTab) {
        return allDatasets.find((tab) => tab.panel === evTab.dataset) || allDatasets[0]
      }
    }
    return allDatasets.find((tab) => tab.panel === selectedDatasetKey.value) || allDatasets[0]
  })

  // Props for the selected tab (Log Explorer)
  const selectedTabProps = computed(() => {
    const { panel } = selectedTab.value
    return props[panel] || {}
  })

  // ── Dashboard panel service resolution ──
  const dashboardListService = computed(() => {
    if (!activePanelConfig.value?.eventsConfig?.dataset) return () => Promise.resolve({ data: [] })
    const dataset = activePanelConfig.value.eventsConfig.dataset
    const tab = allDatasets.find((datasetTab) => datasetTab.dataset === dataset)
    if (tab) {
      const tabProps = props[tab.panel]
      return tabProps?.listService || (() => Promise.resolve({ data: [] }))
    }
    return () => Promise.resolve({ data: [] })
  })

  // ── Existing Log Explorer logic ──
  const handleDatasetChange = async (dataset) => {
    if (dataset && dataset.panel !== selectedDatasetKey.value) {
      selectedDatasetKey.value = dataset.panel
      await updateRouter(dataset.tabRouter)
      await reloadFilterFields(dataset)
      tabPanelBlockRef.value?.reloadListTable()
    }
  }

  const updateRouter = async (tabRouter) => {
    const { name, query, params } = route
    await router.push({
      name,
      params: {
        ...params,
        tab: tabRouter
      },
      query
    })
  }

  const initializeTabSelection = async () => {
    const { params } = route
    if (params.tab) {
      const found = allDatasets.find((tab) => tab.tabRouter === params.tab)
      if (found) {
        selectedDatasetKey.value = found.panel
        return
      }
    }
    // Default to first dataset
    selectedDatasetKey.value = allDatasets[0]?.panel
  }

  const reloadFilterFields = async (tabSelected) => {
    if (!tabSelected?.dataset) return
    generatedFilterFields.value = await loadEventsFilterFields(tabSelected.dataset)
  }

  // ── Task 16.5: Watch activeTabId to sync URL hash / reload filter fields ──
  watch(activeTabId, async (newId) => {
    if (!newId || !isEventsTabId(newId)) return
    // When switching to an additional Events tab, reload filter fields
    // for the tab's dataset
    const tab = eventsTabs.value.find((entry) => entry.id === newId)
    if (tab) {
      const tabConfig = Object.values(TABS_EVENTS).find((entry) => entry.panel === tab.dataset)
      if (tabConfig) {
        await reloadFilterFields(tabConfig)
      }
    }
  })

  // ── Watch activePanel to load filter fields when switching tabs ──
  watch(activePanel, async (newPanelId) => {
    if (newPanelId && isEventsTabId(newPanelId)) {
      // Handled by the activeTabId watcher above
      return
    }
    if (newPanelId && activePanelConfig.value?.eventsConfig?.dataset) {
      // Switching to a dashboard panel
      const dataset = activePanelConfig.value.eventsConfig.dataset
      const tab = allDatasets.find((datasetTab) => datasetTab.dataset === dataset)
      if (tab) {
        await reloadFilterFields(tab)
      }
    } else if (!newPanelId) {
      // Switching back to the Events (Log Explorer) tab — reload fields
      // for the currently selected dataset so the sidebar is correct.
      await reloadFilterFields(selectedTab.value)
    }
  })

  // ── Initialize ──
  onMounted(async () => {
    initializePanels()
    restoreEventsTabs()
    await initializeTabSelection()
    reloadFilterFields(selectedTab.value)
  })
</script>

<style scoped>
  /* Hide TabPanel body content — we render content separately via KeepAlive.
     Everything else (colors, padding, active underline, hover, focus) is
     owned by the PrimeVue @aziontech/theme, matching every other TabView
     in the app. */
  :deep(.rte-events-tabview .p-tabview-panels) {
    display: none;
  }

  /* Suppress the theme's focus ring on mouse-click; keep it for keyboard
     (:focus-visible) so a11y navigation still gets the DS ring. */
  :deep(.rte-events-tabview .p-tabview-nav-link:focus:not(:focus-visible)) {
    box-shadow: none;
    outline: none;
  }

  /* Force square (not circular) shape on all text icon-only buttons
     in the toolbar. PrimeVue's default icon-only hover renders a circle. */
  :deep([data-testid='session-toolbar'] .p-button.p-button-text.p-button-icon-only),
  :deep([data-testid='session-toolbar'] .p-button.p-button-text) {
    border-radius: 4px !important;
  }
</style>
