name: Prod E2E Tests

on:
  workflow_dispatch:

jobs:
  run-prod-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          PROD_CYPRESS_EMAIL: ${{ secrets.PROD_CYPRESS_EMAIL }}
          PROD_CYPRESS_PASSWORD: ${{ secrets.PROD_CYPRESS_PASSWORD }}
        with:
          browser: chrome
          config: cypress.config.prod.js
          env: environment=prod

      - name: Check E2E Test Coverage
        run: node ./scripts/check_coverage.js ./coverage/e2e/lcov.info 20

      - name: Remove lcov intermediate files
        run: |
          rm -rf coverage/e2e/lcov-report
          zip -r coverage.zip coverage

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage_e2e_report
          path: coverage.zip
          retention-days: 7

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: cypress_screenshots
          path: cypress/screenshots
          retention-days: 4

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: cypress_videos
          path: cypress/videos
          retention-days: 1
