name: Dev E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - dev

jobs:
  run-dev-e2e-tests:
    name: Run Dev E2E Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [2, 3, 4, 5, 6, 7]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        env:
          DEV_CYPRESS_EMAIL: ${{ secrets.DEV_CYPRESS_EMAIL }}
          DEV_CYPRESS_PASSWORD: ${{ secrets.DEV_CYPRESS_PASSWORD }}
        with:
          build: yarn build
          start: yarn dev --logLevel=warn
          browser: chrome
          wait-on: 'http://localhost:5173/'
          wait-on-timeout: 120
          env: grepTags=@dev${{ matrix.group }}+-@xfail

      - name: Generate Specs JSON
        run: yarn generate-specs-json

      - name: Validate Specs Tags
        run: node ./scripts/check_tags.js specs.json

      - name: Move Coverage Files
        run: mv .nyc_output/out.json .nyc_output/out_${{ matrix.group }}.json

      - name: Upload Cypress Screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cypress_screenshots_${{ matrix.group }}
          path: cypress/screenshots
          retention-days: 4

      - name: Upload Cypress Videos
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cypress_videos_${{ matrix.group }}
          path: cypress/videos
          retention-days: 1

      - name: Upload Coverage Files
        uses: actions/upload-artifact@v3
        with:
          name: coverage_reportx
          path: .nyc_output/*
          retention-days: 1

  download_and_merge:
    name: Download and Merge Coverage Reports
    needs: run-dev-e2e-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --global nyc

      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v3
        with:
          path: coverage_report

      - name: Merge Coverage Reports
        run: npx nyc merge ./coverage_report/coverage_reportx .nyc_output/out.json

      - name: Generate Text Coverage Report
        run: npx nyc report --reporter=text-summary

      - name: Generate HTML Coverage Report
        run: npx nyc report --reporter=html --report-dir=./coverage/e2e

      - name: Generate LCOV Report
        run: npx nyc report --reporter=lcovonly --report-dir=./coverage/e2e

      - name: Check E2E Test Coverage
        if: ${{ always() }}
        run: node ./scripts/check_coverage.js ./coverage/e2e/lcov.info 20

      - name: Compress Coverage Reports
        if: ${{ always() }}
        run: zip -r coverage.zip coverage

      - name: Upload Coverage Report Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage_e2e_report
          path: coverage.zip
          retention-days: 7
