name: Dev E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - dev

jobs:
  run-dev-e2e-tests:
    name: Run Dev E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [2,3,4,5,6]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        env:
          DEV_CYPRESS_EMAIL: ${{ secrets.DEV_CYPRESS_EMAIL }}
          DEV_CYPRESS_PASSWORD: ${{ secrets.DEV_CYPRESS_PASSWORD }}
        with:
          build: yarn build
          start: yarn dev --logLevel=warn
          browser: chrome
          wait-on: 'http://localhost:5173/'
          wait-on-timeout: 30
          env: grepTags=@dev${{ matrix.group }}+-@xfail

      - name: List files
        run: |
          find ./ | grep -v "node_modules"
          mv .nyc_output/out.json .nyc_output/out_${{ matrix.group }}.json

      - uses: actions/upload-artifact@v3
        with:
          name: coverage_reportx
          path: |
              .nyc_output/*
          retention-days: 1

  download_and_merge:
    needs: run-dev-e2e-tests
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout Code  # You likely need the code for NYC config
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Or your desired version

      - name: Install Dependencies (Including NYC)
        run: npm install --global nyc  # Install NYC globally for easier access

      - name: Download All Coverage Artifacts
        uses: actions/download-artifact@v3
        with:
          path: coverage_report

      - name: List files
        run: |
          find ./ | grep -v "node_modules"
          mkdir .nyc_output
          npx nyc merge ./coverage_report/coverage_reportx .nyc_output/out.json
      
      - name: Coverage file
        run: |
          echo "########################"
          pwd
          echo "########################"
          cat .nyc_output/out.json
          echo "########################"

      - name: Text Report
        run: |
          npx nyc report --reporter=text-summary

      - name: HTML report
        run: |
          npx nyc report --reporter=html --report-dir=./coverage/e2e
      
      - name: List files
        run: |
          find ./ | grep -v "node_modules"

      - name: Check E2E Test Coverage
        if: ${{ always() }}
        run: node ./scripts/check_coverage.js ./coverage/e2e/lcov.info 20

      - name: Compress E2E Coverage Reports
        if: ${{ always() }}
        run: |
          rm -rf coverage/e2e/lcov-report
          zip -r coverage.zip coverage

      - name: Upload E2E Coverage Report Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage_e2e_report
          path: coverage.zip
          retention-days: 7

      - name: Upload Cypress Screenshots Artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cypress_screenshots
          path: cypress/screenshots
          retention-days: 4

      - name: Upload Cypress Videos Artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cypress_videos
          path: cypress/videos
          retention-days: 1
