name: Run Linters And Checking Build Integrity
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - dev
env:
  HUSKY: 0

jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine

    steps:
      - name: Install SO Dependencies
        run: apk add --no-cache curl bash git

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Install Dependencies
        run: yarn install:lock

      - name: Run Prettier Formatting
        run: yarn prettier --check src/

      - name: Run ESLint
        run: yarn lint
      
      - name: Checking Build Integrity
        run: |
          yarn build
          rm -rf dist
          rm -rf coverage