name: Failed E2E Tests

on:
  schedule:
    - cron: '0 3 * * 1-5' # Runs at 00:00 in UTC-3 
  workflow_dispatch:

jobs:
  run-failed-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          STAGE_CYPRESS_EMAIL: ${{ secrets.STAGE_CYPRESS_EMAIL }}
          STAGE_CYPRESS_PASSWORD: ${{ secrets.STAGE_CYPRESS_PASSWORD }}
        with:
          browser: chrome
          config-file: cypress.config.stage.js
          env: environment=stage grepTags=@xfail

      - name: Upload Manual Cypress Screenshots
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: cypress_screenshots
          path: cypress/screenshots
          retention-days: 4

      - name: Upload Manual Cypress Videos
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: cypress_videos
          path: cypress/videos
          retention-days: 1