name: Package Audit

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - dev
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  package-audit:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install SO deps
        run: apk add curl bash git
      
      - name: Install dependencies
        run: yarn ci
      
      - name: Run package-auditor
        run: yarn package-audit
