name: Run Tests and SonarQube Analysis

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - dev

env:
  HUSKY: 0

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: self-hosted
    container:
      image: node:18-alpine3.18

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SO dependencies
        run: apk add curl bash git

      - name: Install dependencies
        run: yarn ci

      - name: Run lint
        run: yarn lint

      - name: Run unit tests
        run: yarn test:unit:headless

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage_unit_report
          path: |
            coverage/lcov.info
            coverage/sonar-report.xml
          retention-days: 1

  sonarqube-analysis:
    name: SonarQube Analysis
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: run-tests
    runs-on: [self-hosted, sonarqube]
    timeout-minutes: 5
    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage_unit_report

      - name: Fix code coverage paths - lcov.info
        run: |
          sed -i 's:/__w/credentials-ui/credentials-ui/:/github/workspace/:' lcov.info
          sed -i 's:/__w/credentials-ui/credentials-ui/:/github/workspace/:' sonar-report.xml
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
